CREATE DATABASE IF NOT EXISTS EventFinderDB;   
USE EventFinderDB;   

 
CREATE TABLE IF NOT EXISTS users (   
 user_id INT AUTO_INCREMENT PRIMARY KEY,   
 username VARCHAR(30) UNIQUE NOT NULL,
 first_name VARCHAR(50) NOT NULL,   
 last_name VARCHAR(50) NOT NULL,   
 email VARCHAR(100) NOT NULL,
 pass_hash VARCHAR(255) NOT NULL
);   

CREATE TABLE IF NOT EXISTS events (
 event_id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT NOT NULL,
 title VARCHAR(100) NOT NULL,
 descr VARCHAR(255) NOT NULL,
 event_date DATETIME NOT NULL,
 event_loc VARCHAR(255) NOT NULL,
 category VARCHAR(20) NOT NULL,
 latitude DOUBLE(9,6) NOT NULL,
 longitude DOUBLE(9,6) NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bookmarks (
 user_id INT NOT NULL,
 event_id INT NOT NULL,
 notify_date DATETIME NOT NULL,
 is_notified BOOLEAN DEFAULT FALSE,
 FOREIGN KEY (user_id) REFERENCES users(user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 FOREIGN KEY (event_id) REFERENCES events(event_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

GRANT ALL PRIVILEGES ON EventFinderDB.* TO 'student'@'%' IDENTIFIED BY 'UApass50';  
FLUSH PRIVILEGES; 
